[phases.setup]
nixPkgs = ["...", "nodejs_23"]

[phases.frontend_install]
dependsOn = ["install"]
cmds = ["cd frontend && rm -f package-lock.json && npm install"]

[phases.frontend_build]
dependsOn = ["frontend_install"]
cmds = ["cd frontend && npm run build"]

[phases.build]
dependsOn = ["frontend_build"]
cmds = [
  "DJANGO_SETTINGS_MODULE=tracking_expenses.settings_prod python manage.py collectstatic --noinput"
]
