[phases.setup]
nixPkgs = ["python313", "nodejs_22"]

[phases.install]
cmds = ["pip install -r requirements.txt", "cd frontend && npm install"]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "DJANGO_SETTINGS_MODULE=tracking_expenses.settings_prod python manage.py collectstatic --noinput",
  "DJANGO_SETTINGS_MODULE=tracking_expenses.settings_prod python manage.py migrate"
]
